version: '3.1'
services:
  postgres:
    container_name: testbot
    image: postgres:14.2
    ports:
      - '5438:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'fa4sd#fas2452cvb'
